name: wallet
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  flutter_screenutil: ^5.8.4
  get_storage: ^2.1.1
  get: ^4.6.5
  intl: ^0.18.1
  flutter_svg: ^2.0.7
  flutter_chat_ui: ^1.6.8
  lottie: ^2.4.0
  badges: ^3.1.1
  flutter_local_notifications: ^15.1.0+1
  animated_flip_counter: ^0.2.5
  draggable_home: ^1.0.4
  liquid_pull_to_refresh: ^3.0.1
  logger: ^1.3.0
  animated_toggle_switch: ^0.7.0
  local_auth: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: MiSans
      fonts:
        - asset: assets/fonts/MiSans-ExtraLight.ttf
          weight: 200

        - asset: assets/fonts/MiSans-Medium.ttf
          weight: 400

        - asset: assets/fonts/MiSans-Semibold.ttf
          weight: 600

flutter_native_splash:
  color: "#000000"
  image: assets/logo.png
  android: false
  ios: false