name: wallet
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  flutter_screenutil: ^5.8.4
  get_storage: ^2.1.1
  get: ^4.6.5
  flutter_svg: ^2.0.7
  flutter_chat_ui: ^1.6.8
  lottie: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/

  fonts:
    - family: MiSans
      fonts:
        - asset: assets/fonts/MiSans-ExtraLight.ttf
          weight: 200

        - asset: assets/fonts/MiSans-Medium.ttf
          weight: 400

        - asset: assets/fonts/MiSans-Semibold.ttf
          weight: 600

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  color: "#000000"
  image: assets/logo.png
  # branding: assets/logo.png
  color_dark: "#000000"
  image_dark: assets/logo.png
  # branding_dark: assets/logo.png

  android_12:
    image: assets/logo.png
    icon_background_color: "#000000"
    image_dark: assets/logo.png
    icon_background_color_dark: "#000000"

  web: false