name: wallet
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.10

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1        #* 生成图标
  flutter_native_splash: ^2.3.1          #* 生成启动图
  flutter_screenutil: ^5.8.4             #* 屏幕适配
  get_storage: ^2.1.1                   #* 本地存储
  get: ^4.6.5                           #* 状态管理
  intl: ^0.18.0                         #* 时间格式化
  flutter_svg: ^2.0.7                    #* svg
  flutter_chat_ui: ^1.6.8                #* 聊天界面
  lottie: ^2.4.0                        #* lottie动画
  badges: ^3.1.1                        #* 徽章
  flutter_local_notifications: ^15.1.0+1  #* 本地通知
  animated_flip_counter: ^0.2.5          #* 数字翻转
  draggable_home: ^1.0.4                #* 拖拽
  liquid_pull_to_refresh: ^3.0.1        #* 下拉刷新
  logger: ^1.3.0                        #* 日志
  animated_toggle_switch: ^0.7.0        #* 开关
  local_auth: ^2.1.6                    #* 生物识别
#  modal_bottom_sheet: ^2.0.0            #* 底部弹窗
  fluttertoast: ^8.2.2                   #* toast
  password_strength: ^0.2.0             #* 密码强度
  loading_animation_widget: ^1.2.0+4    #* 加载动画
  flutter_easyloading: ^3.0.5            #* 加载动画
  flutter_animated_dialog: ^2.0.1        #* 弹窗
  bip39: ^1.0.6                         #* 生成助记词
  bip32: ^2.0.0                         #* 生成私钥
  json_rpc_2: ^3.0.2                    #* json rpc
  web3dart: ^2.7.1                      #* web3
  hex: ^0.2.0                           #* hex
  qr_flutter: ^4.0.0                     #* 二维码
  mobile_scanner: ^3.3.0                #* 扫码
  flutter_slidable: ^3.0.0               #* 滑动删除
  image_picker: ^1.0.1                  #* 图片选择
  camera: ^0.10.5+2                     #* 相机
  path_provider: ^2.0.15                #* 文件路径
  path: ^1.8.3                          #* 文件路径
  video_player: ^2.7.0                  #* 视频播放
  dropdown_button2: ^2.3.6              #* 下拉框
  flutter_localization: ^0.1.13          #* 多语言
  step_progress_indicator: ^1.0.2       #* 进度条
  flutter_secure_storage: ^8.0.0         #* 安全存储
  encrypt: ^5.0.1                       #* 加密
  flutter_qr_reader: ^1.0.5              #* 扫码
  audioplayers: ^5.1.0                  #* 扫码提示音
  http: ^1.1.0                          #* http
  rounded_loading_button: ^2.0.8
  event_bus: ^2.0.0
  dio: ^5.1.2
  azlistview: ^2.0.0
  lpinyin: ^2.0.3
  pin_code_fields: ^7.4.0
  flutter_pickers: ^2.1.9
  pull_to_refresh: ^2.0.0
  grouped_list: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: MiSans
      fonts:
        - asset: assets/fonts/MiSans-ExtraLight.ttf
          weight: 200

        - asset: assets/fonts/MiSans-Medium.ttf
          weight: 400

        - asset: assets/fonts/MiSans-Semibold.ttf
          weight: 600

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"

flutter_native_splash:
  color: "#000000"
  image: assets/images/logo.png
  android: false
  ios: false