name: wallet
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1        #* 生成图标
  flutter_native_splash: ^2.3.1          #* 生成启动图
  flutter_screenutil: ^5.8.4             #* 屏幕适配
  get_storage: ^2.1.1                   #* 本地存储
  get: ^4.6.5                           #* 状态管理
  intl: ^0.18.1                         #* 时间格式化
  flutter_svg: ^2.0.7                    #* svg
  flutter_chat_ui: ^1.6.8                #* 聊天界面
  lottie: ^2.4.0                        #* lottie动画
  badges: ^3.1.1                        #* 徽章
  flutter_local_notifications: ^15.1.0+1  #* 本地通知
  animated_flip_counter: ^0.2.5          #* 数字翻转
  draggable_home: ^1.0.4                #* 拖拽
  liquid_pull_to_refresh: ^3.0.1        #* 下拉刷新
  logger: ^1.3.0                        #* 日志
  animated_toggle_switch: ^0.7.0        #* 开关
  local_auth: ^2.1.6                    #* 生物识别
  modal_bottom_sheet: ^2.1.2            #* 底部弹窗
  password_strength: ^0.2.0             #* 密码强度
  loading_animation_widget: ^1.2.0+4    #* 加载动画
  flutter_easyloading: ^3.0.5            #* 加载动画
  flutter_animated_dialog: ^2.0.1        #* 弹窗
  bip39: ^1.0.6                         #* 生成助记词

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: MiSans
      fonts:
        - asset: assets/fonts/MiSans-ExtraLight.ttf
          weight: 200

        - asset: assets/fonts/MiSans-Medium.ttf
          weight: 400

        - asset: assets/fonts/MiSans-Semibold.ttf
          weight: 600

flutter_native_splash:
  color: "#000000"
  image: assets/logo.png
  android: false
  ios: false